name: easynote
services:
  - name: backend
    http_port: 8080
    image:
      registry_type: DOCR
      repository: agile/backend
      digest: ${BACKEND_DIGEST}
    envs:
      - key: MONGODB_URI
        value: ${MONGO_URI}
      - key: TRANSCRIBE_API_KEY
        value: ${TRANSCRIBE_API_KEY}
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
        
  - name: frontend
    http_port: 8080
    image:
      registry_type: DOCR
      repository: agile/frontend
      digest: ${FRONTEND_DIGEST}
ingress:
  rules:
  - component:
      name: backend
    match:
      path:
        prefix: /api
  - component:
      name: frontend
    match:
      path:
        prefix: / 
